"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-07-16 18:21:38.743020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limiar_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_veiculo', sa.String(), nullable=False),
    sa.Column('tipo_manutencao', sa.String(), nullable=False),
    sa.Column('limite_km', sa.Integer(), nullable=False),
    sa.Column('limite_dias', sa.Integer(), nullable=False),
    sa.Column('antecedencia_km', sa.Integer(), nullable=False),
    sa.Column('antecedencia_dias', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_limiar_config')),
    sa.UniqueConstraint('tipo_veiculo', 'tipo_manutencao', name='tipo_tipo')
    )
    op.create_table('log_qualidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fonte', sa.String(), nullable=False),
    sa.Column('registro_bruto', sa.Text(), nullable=False),
    sa.Column('motivo_rejeicao', sa.String(), nullable=False),
    sa.Column('carga_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_qualidade'))
    )
    op.create_table('stg_abastecimento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carga_em', sa.DateTime(), nullable=False),
    sa.Column('fonte_origem', sa.Text(), nullable=False),
    sa.Column('placa', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('litros', sa.Text(), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('condutor', sa.Text(), nullable=True),
    sa.Column('km', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stg_abastecimento'))
    )
    op.create_table('stg_licenciamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carga_em', sa.DateTime(), nullable=False),
    sa.Column('fonte_origem', sa.Text(), nullable=False),
    sa.Column('placa', sa.Text(), nullable=True),
    sa.Column('vencimento', sa.Text(), nullable=True),
    sa.Column('situacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stg_licenciamento'))
    )
    op.create_table('stg_manutencao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carga_em', sa.DateTime(), nullable=False),
    sa.Column('fonte_origem', sa.Text(), nullable=False),
    sa.Column('placa', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.Column('km_no_momento', sa.Text(), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('aba_origem', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stg_manutencao'))
    )
    op.create_table('stg_multas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carga_em', sa.DateTime(), nullable=False),
    sa.Column('fonte_origem', sa.Text(), nullable=False),
    sa.Column('placa', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('gravidade', sa.Text(), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('condutor', sa.Text(), nullable=True),
    sa.Column('cnh', sa.Text(), nullable=True),
    sa.Column('situacao', sa.Text(), nullable=True),
    sa.Column('codigo_infracao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stg_multas'))
    )
    op.create_table('veiculo',
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('tipo_veiculo', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('secretaria', sa.String(), nullable=True),
    sa.Column('km_atual', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fonte_origem', sa.String(), nullable=False),
    sa.CheckConstraint("tipo_veiculo IN ('leve','ambulancia','caminhao')", name=op.f('ck_veiculo_tipo_veiculo')),
    sa.CheckConstraint('length(placa) = 7', name=op.f('ck_veiculo_placa_len')),
    sa.PrimaryKeyConstraint('placa', name=op.f('pk_veiculo'))
    )
    op.create_table('abastecimento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('litros', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('km_hodometro', sa.Integer(), nullable=True),
    sa.Column('condutor_pseudo', sa.String(), nullable=True),
    sa.Column('fonte_origem', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['placa'], ['veiculo.placa'], name=op.f('fk_abastecimento_placa_veiculo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abastecimento')),
    sa.UniqueConstraint('placa', 'data', 'km_hodometro', name='placa_data_km')
    )
    with op.batch_alter_table('abastecimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abastecimento_placa'), ['placa'], unique=False)
        batch_op.create_index('ix_abastecimento_placa_data', ['placa', 'data'], unique=False)

    op.create_table('alerta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('limiar_id', sa.Integer(), nullable=True),
    sa.Column('tipo_gatilho', sa.String(), nullable=False),
    sa.Column('gerado_em', sa.DateTime(), nullable=False),
    sa.Column('situacao', sa.String(), server_default='ativo', nullable=False),
    sa.Column('detalhe', sa.String(), nullable=True),
    sa.CheckConstraint("situacao IN ('ativo','resolvido')", name=op.f('ck_alerta_situacao')),
    sa.CheckConstraint("tipo_gatilho IN ('km','tempo','dados_insuficientes')", name=op.f('ck_alerta_tipo_gatilho')),
    sa.ForeignKeyConstraint(['limiar_id'], ['limiar_config.id'], name=op.f('fk_alerta_limiar_id_limiar_config')),
    sa.ForeignKeyConstraint(['placa'], ['veiculo.placa'], name=op.f('fk_alerta_placa_veiculo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerta'))
    )
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerta_placa'), ['placa'], unique=False)
        batch_op.create_index('ix_alerta_situacao', ['situacao'], unique=False)

    # Ajuste manual (research R6): índice único parcial por expressão — o autogenerate
    # não o emite em SQLite ("can't reflect these indexes"). Garante no máximo 1 alerta
    # ativo por (placa, gatilho, limiar); coalesce(-1) faz NULLs de limiar_id conflitarem.
    op.create_index(
        'ux_alerta_ativo',
        'alerta',
        ['placa', 'tipo_gatilho', sa.text('coalesce(limiar_id, -1)')],
        unique=True,
        sqlite_where=sa.text("situacao = 'ativo'"),
        postgresql_where=sa.text("situacao = 'ativo'"),
    )

    op.create_table('licenciamento',
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.Column('fonte_origem', sa.String(), nullable=False),
    sa.CheckConstraint("situacao IN ('em_dia','vencido')", name=op.f('ck_licenciamento_situacao')),
    sa.ForeignKeyConstraint(['placa'], ['veiculo.placa'], name=op.f('fk_licenciamento_placa_veiculo')),
    sa.PrimaryKeyConstraint('placa', name=op.f('pk_licenciamento'))
    )
    with op.batch_alter_table('licenciamento', schema=None) as batch_op:
        batch_op.create_index('ix_licenciamento_vencimento', ['vencimento'], unique=False)

    op.create_table('manutencao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('km_no_momento', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fonte_origem', sa.String(), nullable=False),
    sa.CheckConstraint("categoria IN ('preventiva','corretiva')", name=op.f('ck_manutencao_categoria')),
    sa.CheckConstraint("tipo IN ('troca_oleo','filtros','pneus','revisao_geral')", name=op.f('ck_manutencao_tipo')),
    sa.ForeignKeyConstraint(['placa'], ['veiculo.placa'], name=op.f('fk_manutencao_placa_veiculo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manutencao')),
    sa.UniqueConstraint('placa', 'data', 'tipo', name='placa_data_tipo')
    )
    with op.batch_alter_table('manutencao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manutencao_placa'), ['placa'], unique=False)
        batch_op.create_index('ix_manutencao_placa_tipo_data', ['placa', 'tipo', 'data'], unique=False)

    op.create_table('multa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('condutor_pseudo', sa.String(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=False),
    sa.Column('fonte_origem', sa.String(), nullable=False),
    sa.CheckConstraint("situacao IN ('pendente','paga')", name=op.f('ck_multa_situacao')),
    sa.ForeignKeyConstraint(['placa'], ['veiculo.placa'], name=op.f('fk_multa_placa_veiculo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_multa')),
    sa.UniqueConstraint('placa', 'data', 'valor', 'condutor_pseudo', name='placa_data_valor_condutor')
    )
    with op.batch_alter_table('multa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_multa_placa'), ['placa'], unique=False)
        batch_op.create_index('ix_multa_placa_data', ['placa', 'data'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multa', schema=None) as batch_op:
        batch_op.drop_index('ix_multa_placa_data')
        batch_op.drop_index(batch_op.f('ix_multa_placa'))

    op.drop_table('multa')
    with op.batch_alter_table('manutencao', schema=None) as batch_op:
        batch_op.drop_index('ix_manutencao_placa_tipo_data')
        batch_op.drop_index(batch_op.f('ix_manutencao_placa'))

    op.drop_table('manutencao')
    with op.batch_alter_table('licenciamento', schema=None) as batch_op:
        batch_op.drop_index('ix_licenciamento_vencimento')

    op.drop_table('licenciamento')
    op.drop_index('ux_alerta_ativo', table_name='alerta')
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.drop_index('ix_alerta_situacao')
        batch_op.drop_index(batch_op.f('ix_alerta_placa'))

    op.drop_table('alerta')
    with op.batch_alter_table('abastecimento', schema=None) as batch_op:
        batch_op.drop_index('ix_abastecimento_placa_data')
        batch_op.drop_index(batch_op.f('ix_abastecimento_placa'))

    op.drop_table('abastecimento')
    op.drop_table('veiculo')
    op.drop_table('stg_multas')
    op.drop_table('stg_manutencao')
    op.drop_table('stg_licenciamento')
    op.drop_table('stg_abastecimento')
    op.drop_table('log_qualidade')
    op.drop_table('limiar_config')
    # ### end Alembic commands ###
